version: "3"
networks:
  default:
    external:
      name: crypto-scraper_default

services:      
  scraper:
    build:
      context: ../../src/
      dockerfile: ../docker/dev/Dockerfile-be
    image: crypto_corvid_backend
    entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
    env_file:
      - ../../src/.env
    environment:
      - DB_HOST=db
    volumes:
      - ../../src:/crypto-app
    depends_on:
      - kafka
      - db
      - graylog

  wallet-explorer:
    image: crypto_corvid_backend
    entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
    env_file:
      - ../../src/.env
    command: fetch_wallet_explorer
    volumes:
      - ../../src:/crypto-app
    depends_on:
      - db
      - graylog
