FROM php:7.4.6-cli-alpine3.11

RUN apk update && apk add openssl zip unzip git postgresql-dev librdkafka-dev bash $PHPIZE_DEPS
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_pgsql
RUN pecl install rdkafka
#RUN pecl install xdebug
RUN docker-php-ext-enable rdkafka
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN echo "extension=rdkafka.so" >> /usr/local/etc/php/php.ini
#RUN echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so"' >> /usr/local/etc/php/php.ini

WORKDIR /crypto-app
COPY ./wait-for-it.sh /crypto-app

