FROM php:7.4.6-cli-alpine3.11

RUN apk update && apk add openssl zip unzip git postgresql-dev librdkafka-dev bash $PHPIZE_DEPS
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_pgsql
RUN pecl install rdkafka
RUN docker-php-ext-enable rdkafka
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN echo "extension=rdkafka.so" >> /usr/local/etc/php/php.ini

WORKDIR /crypto-app
COPY . /crypto-app

ENV DB_HOST db
ENV DEBUGBAR_ENABLED false

RUN composer global require hirak/prestissimo
RUN composer install --no-dev

RUN php artisan config:cache
