FROM php:7.4.2

RUN apt-get update -y && apt-get install -y openssl zip unzip git libpq-dev libjudy-dev librdkafka-dev
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_pgsql
RUN pecl install rdkafka
RUN pecl install memprof
RUN pecl install xdebug
RUN docker-php-ext-enable rdkafka
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN echo "extension=rdkafka.so" >> /usr/local/etc/php/php.ini
RUN echo "extension=memprof.so" >> /usr/local/etc/php/php.ini
RUN echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so"' >> /usr/local/etc/php/php.ini

WORKDIR /crypto-app
COPY . /crypto-app

