version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "crypto_scraper_pg"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scraper
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  
  laravel:
    tty: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:8181
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
  