version: "3"
services:
  laravel:
#    command: php artisan bitcointalk:board_consumer
    volumes:
      - .:/app
    working_dir: /app
#    command: php run_producer.php
#    command: php run_consumer.php

  producer:
    command: php artisan bitcointalk:board_producer
    image: crypto-scraper_laravel
    volumes:
      - ./:/app
    links:
      - db
      - kafka
    depends_on:
      - db
      - kafka

  consumer:
#    command: php artisan bitcointalk:board_consumer
    command: php artisan consumer:scrape scrapeGroup bitcointalkScrapes 
    image: crypto-scraper_laravel
    volumes:
      - ./:/app
    links:
      - db
      - kafka
    depends_on:
      - db
      - kafka
        
        
        
#  docker-compose -f common.yml -f dev.yml run consumer --entrypoint php artisan consumer:scrape scrapeGroup bitcointalkScrapes
