version: "3.7"
networks:
  default:
    external:
      name: crypto-corvid_default

x_scraper_base: &scraper_base
  build:
    context: ../../src/
    dockerfile: ../docker/dev/Dockerfile-be
  image: crypto_corvid_backend
  entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
  env_file:
    - ../../src/.env
  environment:
    - DB_HOST=db
  volumes:
    - ../../src:/crypto-app
  depends_on:
    - kafka
    - db
    - graylog
    - proxy

services:
  all_main_topics_producer:
    << : *scraper_base
    command: "bct:all_main_topics_producer 2"

  un_board_pages_producer:
    << : *scraper_base
    command: "bct:un_board_pages_producer 2"

  un_topic_pages_producer:
    << : *scraper_base
    command: "bct:un_topic_pages_producer 2"

  un_user_profiles_producer:
    << : *scraper_base
    command: "bct:un_user_profiles_producer 2"