version: "3.7"
networks:
  default:
    external:
      name: crypto-corvid_default

x-scraper-base: &scraper-base
  build:
    context: ../../src/
    dockerfile: ../docker/dev/Dockerfile-be
  image: crypto_corvid_backend
  entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
  env_file:
    - ../../src/.env
  environment:
    - DB_HOST=db
  volumes:
    - ../../src:/crypto-app
  depends_on:
    - kafka
    - db
    - graylog
    - proxy

services:
  main-boards-producer:
    << : *scraper-base
    command: "bct:main_boards_producer 2"

  board-pages-producer:
    << : *scraper-base
    command: "bct:board_pages_producer 2"

  main-topics-producer:
    << : *scraper-base
    command: "bct:main_topics_producer 2"

  topic-pages-producer:
    << : *scraper-base
    command: "bct:topic_pages_producer 2"

  user-profiles-producer:
    << : *scraper-base
    command: "bct:user_profiles_producer 2"

  topic-pages-consumer:
    << : *scraper-base
    command: "bct:topic_pages_consumer 2"

  user-profiles-consumer:
    << : *scraper-base
    command: "bct:board_pages_producer 2"
  