version: "3.7"
networks:
  default:
    external:
      name: crypto-corvid_default
      
x-scraper-base: &scraper-base
  build:
    context: ../../src/
    dockerfile: ../docker/dev/Dockerfile-be
  image: crypto_corvid_backend
  entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
  env_file:
    - ../../src/.env
  environment:
    - DB_HOST=db
  volumes:
    - ../../src:/crypto-app
  depends_on:
    - kafka
    - db
    - graylog
    - proxy

services:
  bca_load_csv_data_1d:
    << : *scraper-base
    command: "bca:load_csv_data 2 1d"

  bca_load_csv_data_30d:
    << : *scraper-base
    command: "bca:load_csv_data 2 30d"

  bca_load_csv_data_forever:
    << : *scraper-base
    command: "bca:load_csv_data 2 forever"