version: "3.7"
services:
  migrate:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan migrate
    environment:
      - DB_HOST=db
    depends_on:
      - db

  seed:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan db:seed
    environment:
      - DB_HOST=db
    depends_on:
      - db
        
  composer:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    entrypoint: composer
    command: install
    volumes:
      - ../../src:/crypto-app
