version: "3.7"
networks:
  default:
    external:
      name: crypto-corvid_default
      
x-scraper-base: &scraper_base
  image: crypto_corvid_backend
  entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
  env_file:
    - ../../src/.env
  depends_on:
    - kafka
    - db
    - graylog
    - proxy

services:
  bca_load_csv_data:
    << : *scraper_base
    command: "bca:load_csv_data 2 1d"

  bca_load_csv_data_30d:
    << : *scraper_base
    command: "bca:load_csv_data 2 30d"

  bca_load_csv_data_forever:
    << : *scraper_base
    command: "bca:load_csv_data 2 forever"