version: "3.7"
networks:
  default:
    external:
      name: crypto-corvid_default

x-scraper-base: &scraper_base
  image: crypto_corvid_backend
  entrypoint: ["./wait-for-it.sh", "graylog:9000", "-s", "-t", "120", "--", "php", "artisan"]
  env_file:
    - ../../src/.env
  depends_on:
    - kafka
    - db
    - graylog
    - proxy

services:
  bct_all_main_topics_producer:
    << : *scraper_base
    command: "bct:all_main_topics_producer 2"

  bct_un_board_pages_producer:
    << : *scraper_base
    command: "bct:un_board_pages_producer 2"

  bct_un_main_topics_producer:
    << : *scraper_base
    command: "bct:un_main_topics_producer 2"

  bct_un_topic_pages_producer:
    << : *scraper_base
    command: "bct:un_topic_pages_producer 2"

  bct_un_user_profiles_producer:
    << : *scraper_base
    command: "bct:un_user_profiles_producer 2"