version: "3.7"
services:
  migrate:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan migrate
    depends_on:
      - db

  seed:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan db:seed
    depends_on:
      - db
        
  composer:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    entrypoint: composer
    command: install
        
  schedule:
    image: crypto_corvid_backend
    depends_on:
      - db
    command: php artisan schedule:run
