version: "3.7"
services:
  migrate:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan migrate
    depends_on:
      - db

  seed:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    command: php artisan db:seed
    depends_on:
      - db

  composer_scheduler:
    image: crypto_corvid_backend
    env_file:
      - ../../src/.env
    environment:
      - APP_ENV=production
      - COMPOSER=composer-frontend.json
    entrypoint: composer
    command: install
    volumes:
      - ../../src:/crypto-app
